// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as MongoCodecTypes, Vector } from '@prisma/orm-mongo/adapter/codec-types';

import type {
  MongoCollection,
  MongoContractWithTypeMaps,
  MongoTypeMaps,
} from '@prisma/orm-mongo/family-contract';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-mongo/contract/types';

export type StorageHash =
  StorageHashBase<'37e67d3183ea71867d924caa74123c73ee95c7415bde9b32827c151061bc8f81'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'251b3ce23f6c9f561892e7c1af9d2cc941a13d64ba1aa7226b90036b09568cc3'>;

export type CodecTypes = MongoCodecTypes;

export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly Product: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly name: CodecTypes['mongo/string@1']['output'];
      readonly description: CodecTypes['mongo/string@1']['output'];
      readonly priceCents: CodecTypes['mongo/int32@1']['output'];
      readonly currency: 'EUR' | 'GBP' | 'TRY';
      readonly category: 'ELECTRONICS' | 'CLOTHING' | 'HOME' | 'SPORTS' | 'OTHER';
      readonly stock: CodecTypes['mongo/int32@1']['output'];
      readonly imageUrls: ReadonlyArray<CodecTypes['mongo/string@1']['output']>;
      readonly isActive: CodecTypes['mongo/bool@1']['output'];
      readonly createdAt: CodecTypes['mongo/date@1']['output'];
      readonly updatedAt: CodecTypes['mongo/date@1']['output'];
    };
    readonly User: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly email: CodecTypes['mongo/string@1']['output'];
      readonly firstName: CodecTypes['mongo/string@1']['output'] | null;
      readonly lastName: CodecTypes['mongo/string@1']['output'] | null;
      readonly profilePictureUrl: CodecTypes['mongo/string@1']['output'] | null;
      readonly createdAt: CodecTypes['mongo/date@1']['output'];
      readonly updatedAt: CodecTypes['mongo/date@1']['output'];
      readonly auth0_id: CodecTypes['mongo/string@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly Product: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly name: CodecTypes['mongo/string@1']['input'];
      readonly description: CodecTypes['mongo/string@1']['input'];
      readonly priceCents: CodecTypes['mongo/int32@1']['input'];
      readonly currency: 'EUR' | 'GBP' | 'TRY';
      readonly category: 'ELECTRONICS' | 'CLOTHING' | 'HOME' | 'SPORTS' | 'OTHER';
      readonly stock: CodecTypes['mongo/int32@1']['input'];
      readonly imageUrls: ReadonlyArray<CodecTypes['mongo/string@1']['input']>;
      readonly isActive: CodecTypes['mongo/bool@1']['input'];
      readonly createdAt: CodecTypes['mongo/date@1']['input'];
      readonly updatedAt: CodecTypes['mongo/date@1']['input'];
    };
    readonly User: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly email: CodecTypes['mongo/string@1']['input'];
      readonly firstName: CodecTypes['mongo/string@1']['input'] | null;
      readonly lastName: CodecTypes['mongo/string@1']['input'] | null;
      readonly profilePictureUrl: CodecTypes['mongo/string@1']['input'] | null;
      readonly createdAt: CodecTypes['mongo/date@1']['input'];
      readonly updatedAt: CodecTypes['mongo/date@1']['input'];
      readonly auth0_id: CodecTypes['mongo/string@1']['input'];
    };
  };
};
export type TypeMaps = MongoTypeMaps<CodecTypes, FieldOutputTypes, FieldInputTypes>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'mongo-database';
        readonly entries: {
          readonly collection: {
            readonly products: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly name: { readonly bsonType: 'string' };
                    readonly description: { readonly bsonType: 'string' };
                    readonly priceCents: { readonly bsonType: 'int' };
                    readonly currency: {
                      readonly bsonType: 'string';
                      readonly enum: readonly ['EUR', 'GBP', 'TRY'];
                    };
                    readonly category: {
                      readonly bsonType: 'string';
                      readonly enum: readonly [
                        'ELECTRONICS',
                        'CLOTHING',
                        'HOME',
                        'SPORTS',
                        'OTHER',
                      ];
                    };
                    readonly stock: { readonly bsonType: 'int' };
                    readonly imageUrls: {
                      readonly bsonType: 'array';
                      readonly items: { readonly bsonType: 'string' };
                    };
                    readonly isActive: { readonly bsonType: 'bool' };
                    readonly createdAt: { readonly bsonType: 'date' };
                    readonly updatedAt: { readonly bsonType: 'date' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'category',
                    'createdAt',
                    'currency',
                    'description',
                    'imageUrls',
                    'isActive',
                    'name',
                    'priceCents',
                    'stock',
                    'updatedAt',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly users: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'email'; readonly direction: 1 }];
                  readonly unique: true;
                },
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'auth0_id'; readonly direction: 1 }];
                  readonly unique: true;
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly email: { readonly bsonType: 'string' };
                    readonly firstName: { readonly bsonType: readonly ['null', 'string'] };
                    readonly lastName: { readonly bsonType: readonly ['null', 'string'] };
                    readonly profilePictureUrl: { readonly bsonType: readonly ['null', 'string'] };
                    readonly createdAt: { readonly bsonType: 'date' };
                    readonly updatedAt: { readonly bsonType: 'date' };
                    readonly auth0_id: { readonly bsonType: 'string' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'auth0_id',
                    'createdAt',
                    'email',
                    'updatedAt',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'mongo';
  readonly targetFamily: 'mongo';
  readonly roots: {
    readonly products: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Product';
    };
    readonly users: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'User' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly Product: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly description: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly priceCents: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly currency: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly category: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly stock: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly imageUrls: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
                readonly many: true;
              };
              readonly isActive: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/bool@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'products' };
          };
          readonly User: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly firstName: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly lastName: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly profilePictureUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly auth0_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'users' };
          };
        };
        readonly enum: {
          readonly Currency: {
            readonly codecId: 'mongo/string@1';
            readonly members: readonly [
              { readonly name: 'EUR'; readonly value: 'EUR' },
              { readonly name: 'GBP'; readonly value: 'GBP' },
              { readonly name: 'TRY'; readonly value: 'TRY' },
            ];
          };
          readonly Category: {
            readonly codecId: 'mongo/string@1';
            readonly members: readonly [
              { readonly name: 'ELECTRONICS'; readonly value: 'ELECTRONICS' },
              { readonly name: 'CLOTHING'; readonly value: 'CLOTHING' },
              { readonly name: 'HOME'; readonly value: 'HOME' },
              { readonly name: 'SPORTS'; readonly value: 'SPORTS' },
              { readonly name: 'OTHER'; readonly value: 'OTHER' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {};
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = MongoContractWithTypeMaps<ContractBase, TypeMaps>;
