import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Button } from '@/components/ui/button';
import { auth0 } from '@/lib/auth0';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const session = await auth0.getSession();


  return (
    <html
      lang='en'
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className='min-h-full'>
        <nav>
          <ul className='flex gap-10 justify-end max-w-7xl py-6'>
            {session ? (
              <>
                <li>
                  <Button asChild>
                    <Link href='/user/settings'>Settings</Link>
                  </Button>
                </li>
                <li>
                  <Button asChild>
                    <a href='/auth/logout'>Logout</a>
                  </Button>
                </li>
              </>
            ) : (
              <li>
                <Button asChild>
                  <a href='/auth/login'>Login</a>
                </Button>
              </li>
            )}
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
