// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as MongoCodecTypes } from '@prisma/orm-mongo/target/codec-types';

import type {
  MongoCollection,
  MongoContractWithTypeMaps,
  MongoTypeMaps,
  RelationKeys,
} from '@prisma/orm-mongo/family-contract';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-mongo/contract/types';

export type StorageHash =
  StorageHashBase<'59443ad1ebfa6cf1dc75d69682bd6b9e7ff7752b1a90da7137283ffb0118c839'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'251b3ce23f6c9f561892e7c1af9d2cc941a13d64ba1aa7226b90036b09568cc3'>;

export type CodecTypes = MongoCodecTypes;

export type AddressOutput = {
  readonly city: CodecTypes['mongo/string@1']['output'];
  readonly country: CodecTypes['mongo/string@1']['output'];
  readonly line1: CodecTypes['mongo/string@1']['output'];
  readonly postalCode: CodecTypes['mongo/string@1']['output'];
};
export type AddressInput = {
  readonly city: CodecTypes['mongo/string@1']['input'];
  readonly country: CodecTypes['mongo/string@1']['input'];
  readonly line1: CodecTypes['mongo/string@1']['input'];
  readonly postalCode: CodecTypes['mongo/string@1']['input'];
};
export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly Order: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly address: AddressOutput;
      readonly checkoutSessionId: CodecTypes['mongo/string@1']['output'];
      readonly createdAt: CodecTypes['mongo/date@1']['output'];
      readonly status:
        | 'PENDING'
        | 'PROCESSING'
        | 'SHIPPED'
        | 'DELIVERED'
        | 'CANCELLED'
        | 'RETURNED'
        | 'REFUNDED'
        | 'EXPIRED';
      readonly updatedAt: CodecTypes['mongo/date@1']['output'];
      readonly userId: CodecTypes['mongo/objectId@1']['output'];
    };
    readonly OrderItem: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly createdAt: CodecTypes['mongo/date@1']['output'];
      readonly currency: 'EUR' | 'GBP' | 'TRY';
      readonly orderId: CodecTypes['mongo/objectId@1']['output'];
      readonly priceCents: CodecTypes['mongo/int32@1']['output'];
      readonly productId: CodecTypes['mongo/objectId@1']['output'];
      readonly quantity: CodecTypes['mongo/int32@1']['output'];
      readonly updatedAt: CodecTypes['mongo/date@1']['output'];
    };
    readonly Product: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly category: 'ELECTRONICS' | 'CLOTHING' | 'HOME' | 'SPORTS' | 'OTHER';
      readonly createdAt: CodecTypes['mongo/date@1']['output'];
      readonly currency: 'EUR' | 'GBP' | 'TRY';
      readonly description: CodecTypes['mongo/string@1']['output'];
      readonly imageUrls: ReadonlyArray<CodecTypes['mongo/string@1']['output']>;
      readonly isActive: CodecTypes['mongo/bool@1']['output'];
      readonly name: CodecTypes['mongo/string@1']['output'];
      readonly priceCents: CodecTypes['mongo/int32@1']['output'];
      readonly priceId: CodecTypes['mongo/string@1']['output'];
      readonly productId: CodecTypes['mongo/string@1']['output'];
      readonly stock: CodecTypes['mongo/int32@1']['output'];
      readonly updatedAt: CodecTypes['mongo/date@1']['output'];
    };
    readonly User: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly auth0_id: CodecTypes['mongo/string@1']['output'];
      readonly createdAt: CodecTypes['mongo/date@1']['output'];
      readonly email: CodecTypes['mongo/string@1']['output'];
      readonly firstName: CodecTypes['mongo/string@1']['output'] | null;
      readonly lastName: CodecTypes['mongo/string@1']['output'] | null;
      readonly profilePictureUrl: CodecTypes['mongo/string@1']['output'] | null;
      readonly updatedAt: CodecTypes['mongo/date@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly Order: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly address: AddressInput;
      readonly checkoutSessionId: CodecTypes['mongo/string@1']['input'];
      readonly createdAt: CodecTypes['mongo/date@1']['input'];
      readonly status:
        | 'PENDING'
        | 'PROCESSING'
        | 'SHIPPED'
        | 'DELIVERED'
        | 'CANCELLED'
        | 'RETURNED'
        | 'REFUNDED'
        | 'EXPIRED';
      readonly updatedAt: CodecTypes['mongo/date@1']['input'];
      readonly userId: CodecTypes['mongo/objectId@1']['input'];
    };
    readonly OrderItem: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly createdAt: CodecTypes['mongo/date@1']['input'];
      readonly currency: 'EUR' | 'GBP' | 'TRY';
      readonly orderId: CodecTypes['mongo/objectId@1']['input'];
      readonly priceCents: CodecTypes['mongo/int32@1']['input'];
      readonly productId: CodecTypes['mongo/objectId@1']['input'];
      readonly quantity: CodecTypes['mongo/int32@1']['input'];
      readonly updatedAt: CodecTypes['mongo/date@1']['input'];
    };
    readonly Product: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly category: 'ELECTRONICS' | 'CLOTHING' | 'HOME' | 'SPORTS' | 'OTHER';
      readonly createdAt: CodecTypes['mongo/date@1']['input'];
      readonly currency: 'EUR' | 'GBP' | 'TRY';
      readonly description: CodecTypes['mongo/string@1']['input'];
      readonly imageUrls: ReadonlyArray<CodecTypes['mongo/string@1']['input']>;
      readonly isActive: CodecTypes['mongo/bool@1']['input'];
      readonly name: CodecTypes['mongo/string@1']['input'];
      readonly priceCents: CodecTypes['mongo/int32@1']['input'];
      readonly priceId: CodecTypes['mongo/string@1']['input'];
      readonly productId: CodecTypes['mongo/string@1']['input'];
      readonly stock: CodecTypes['mongo/int32@1']['input'];
      readonly updatedAt: CodecTypes['mongo/date@1']['input'];
    };
    readonly User: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly auth0_id: CodecTypes['mongo/string@1']['input'];
      readonly createdAt: CodecTypes['mongo/date@1']['input'];
      readonly email: CodecTypes['mongo/string@1']['input'];
      readonly firstName: CodecTypes['mongo/string@1']['input'] | null;
      readonly lastName: CodecTypes['mongo/string@1']['input'] | null;
      readonly profilePictureUrl: CodecTypes['mongo/string@1']['input'] | null;
      readonly updatedAt: CodecTypes['mongo/date@1']['input'];
    };
  };
};

export namespace Models {
  export type unbound_Order = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    address: AddressOutput;
    checkoutSessionId: CodecTypes['mongo/string@1']['output'];
    createdAt: CodecTypes['mongo/date@1']['output'];
    status:
      | 'PENDING'
      | 'PROCESSING'
      | 'SHIPPED'
      | 'DELIVERED'
      | 'CANCELLED'
      | 'RETURNED'
      | 'REFUNDED'
      | 'EXPIRED';
    updatedAt: CodecTypes['mongo/date@1']['output'];
    userId: CodecTypes['mongo/objectId@1']['output'];
    orderItems: unbound_OrderItem[];
    user: unbound_User;
    readonly [RelationKeys]?: 'orderItems' | 'user';
  };
  export type unbound_OrderItem = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    createdAt: CodecTypes['mongo/date@1']['output'];
    currency: 'EUR' | 'GBP' | 'TRY';
    orderId: CodecTypes['mongo/objectId@1']['output'];
    priceCents: CodecTypes['mongo/int32@1']['output'];
    productId: CodecTypes['mongo/objectId@1']['output'];
    quantity: CodecTypes['mongo/int32@1']['output'];
    updatedAt: CodecTypes['mongo/date@1']['output'];
    order: unbound_Order;
    product: unbound_Product;
    readonly [RelationKeys]?: 'order' | 'product';
  };
  export type unbound_Product = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    category: 'ELECTRONICS' | 'CLOTHING' | 'HOME' | 'SPORTS' | 'OTHER';
    createdAt: CodecTypes['mongo/date@1']['output'];
    currency: 'EUR' | 'GBP' | 'TRY';
    description: CodecTypes['mongo/string@1']['output'];
    imageUrls: ReadonlyArray<CodecTypes['mongo/string@1']['output']>;
    isActive: CodecTypes['mongo/bool@1']['output'];
    name: CodecTypes['mongo/string@1']['output'];
    priceCents: CodecTypes['mongo/int32@1']['output'];
    priceId: CodecTypes['mongo/string@1']['output'];
    productId: CodecTypes['mongo/string@1']['output'];
    stock: CodecTypes['mongo/int32@1']['output'];
    updatedAt: CodecTypes['mongo/date@1']['output'];
    orderItems: unbound_OrderItem[];
    readonly [RelationKeys]?: 'orderItems';
  };
  export type unbound_User = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    auth0_id: CodecTypes['mongo/string@1']['output'];
    createdAt: CodecTypes['mongo/date@1']['output'];
    email: CodecTypes['mongo/string@1']['output'];
    firstName: CodecTypes['mongo/string@1']['output'] | null;
    lastName: CodecTypes['mongo/string@1']['output'] | null;
    profilePictureUrl: CodecTypes['mongo/string@1']['output'] | null;
    updatedAt: CodecTypes['mongo/date@1']['output'];
    orders: unbound_Order[];
    readonly [RelationKeys]?: 'orders';
  };
}

export declare const models: {
  __unbound__: {
    Order: Models.unbound_Order;
    OrderItem: Models.unbound_OrderItem;
    Product: Models.unbound_Product;
    User: Models.unbound_User;
  };
};

export type TypeMaps = MongoTypeMaps<CodecTypes, FieldOutputTypes, FieldInputTypes>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'mongo-database';
        readonly entries: {
          readonly collection: {
            readonly orders: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly jsonSchema: {
                  readonly additionalProperties: false;
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly address: {
                      readonly additionalProperties: false;
                      readonly bsonType: 'object';
                      readonly properties: {
                        readonly city: { readonly bsonType: 'string' };
                        readonly country: { readonly bsonType: 'string' };
                        readonly line1: { readonly bsonType: 'string' };
                        readonly postalCode: { readonly bsonType: 'string' };
                      };
                      readonly required: readonly ['city', 'country', 'line1', 'postalCode'];
                    };
                    readonly checkoutSessionId: { readonly bsonType: 'string' };
                    readonly createdAt: { readonly bsonType: 'date' };
                    readonly status: {
                      readonly bsonType: 'string';
                      readonly enum: readonly [
                        'PENDING',
                        'PROCESSING',
                        'SHIPPED',
                        'DELIVERED',
                        'CANCELLED',
                        'RETURNED',
                        'REFUNDED',
                        'EXPIRED',
                      ];
                    };
                    readonly updatedAt: { readonly bsonType: 'date' };
                    readonly userId: { readonly bsonType: 'objectId' };
                  };
                  readonly required: readonly [
                    '_id',
                    'address',
                    'checkoutSessionId',
                    'createdAt',
                    'status',
                    'updatedAt',
                    'userId',
                  ];
                };
                readonly kind: 'mongo-validator';
                readonly validationAction: 'error';
                readonly validationLevel: 'strict';
              };
            };
            readonly 'orders-items': {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly jsonSchema: {
                  readonly additionalProperties: false;
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly createdAt: { readonly bsonType: 'date' };
                    readonly currency: {
                      readonly bsonType: 'string';
                      readonly enum: readonly ['EUR', 'GBP', 'TRY'];
                    };
                    readonly orderId: { readonly bsonType: 'objectId' };
                    readonly priceCents: { readonly bsonType: 'int' };
                    readonly productId: { readonly bsonType: 'objectId' };
                    readonly quantity: { readonly bsonType: 'int' };
                    readonly updatedAt: { readonly bsonType: 'date' };
                  };
                  readonly required: readonly [
                    '_id',
                    'createdAt',
                    'currency',
                    'orderId',
                    'priceCents',
                    'productId',
                    'quantity',
                    'updatedAt',
                  ];
                };
                readonly kind: 'mongo-validator';
                readonly validationAction: 'error';
                readonly validationLevel: 'strict';
              };
            };
            readonly products: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly jsonSchema: {
                  readonly additionalProperties: false;
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly category: {
                      readonly bsonType: 'string';
                      readonly enum: readonly [
                        'ELECTRONICS',
                        'CLOTHING',
                        'HOME',
                        'SPORTS',
                        'OTHER',
                      ];
                    };
                    readonly createdAt: { readonly bsonType: 'date' };
                    readonly currency: {
                      readonly bsonType: 'string';
                      readonly enum: readonly ['EUR', 'GBP', 'TRY'];
                    };
                    readonly description: { readonly bsonType: 'string' };
                    readonly imageUrls: {
                      readonly bsonType: 'array';
                      readonly items: { readonly bsonType: 'string' };
                    };
                    readonly isActive: { readonly bsonType: 'bool' };
                    readonly name: { readonly bsonType: 'string' };
                    readonly priceCents: { readonly bsonType: 'int' };
                    readonly priceId: { readonly bsonType: 'string' };
                    readonly productId: { readonly bsonType: 'string' };
                    readonly stock: { readonly bsonType: 'int' };
                    readonly updatedAt: { readonly bsonType: 'date' };
                  };
                  readonly required: readonly [
                    '_id',
                    'category',
                    'createdAt',
                    'currency',
                    'description',
                    'imageUrls',
                    'isActive',
                    'name',
                    'priceCents',
                    'priceId',
                    'productId',
                    'stock',
                    'updatedAt',
                  ];
                };
                readonly kind: 'mongo-validator';
                readonly validationAction: 'error';
                readonly validationLevel: 'strict';
              };
            };
            readonly users: {
              readonly indexes: readonly [
                {
                  readonly keys: readonly [{ readonly direction: 1; readonly field: 'email' }];
                  readonly kind: 'mongo-index';
                  readonly unique: true;
                },
                {
                  readonly keys: readonly [{ readonly direction: 1; readonly field: 'auth0_id' }];
                  readonly kind: 'mongo-index';
                  readonly unique: true;
                },
              ];
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly jsonSchema: {
                  readonly additionalProperties: false;
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly auth0_id: { readonly bsonType: 'string' };
                    readonly createdAt: { readonly bsonType: 'date' };
                    readonly email: { readonly bsonType: 'string' };
                    readonly firstName: { readonly bsonType: readonly ['null', 'string'] };
                    readonly lastName: { readonly bsonType: readonly ['null', 'string'] };
                    readonly profilePictureUrl: { readonly bsonType: readonly ['null', 'string'] };
                    readonly updatedAt: { readonly bsonType: 'date' };
                  };
                  readonly required: readonly [
                    '_id',
                    'auth0_id',
                    'createdAt',
                    'email',
                    'updatedAt',
                  ];
                };
                readonly kind: 'mongo-validator';
                readonly validationAction: 'error';
                readonly validationLevel: 'strict';
              };
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'mongo';
  readonly targetFamily: 'mongo';
  readonly roots: {
    readonly orders: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Order' };
    readonly 'orders-items': {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'OrderItem';
    };
    readonly products: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Product';
    };
    readonly users: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'User' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly Order: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly address: {
                readonly nullable: false;
                readonly type: { readonly kind: 'valueObject'; readonly name: 'Address' };
              };
              readonly checkoutSessionId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
            };
            readonly relations: {
              readonly orderItems: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'OrderItem';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['orderId'];
                };
              };
              readonly user: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
            };
            readonly storage: { readonly collection: 'orders' };
          };
          readonly OrderItem: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly currency: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly orderId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly priceCents: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly productId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly quantity: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: {
              readonly order: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Order';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['orderId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
              readonly product: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Product';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['productId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
            };
            readonly storage: { readonly collection: 'orders-items' };
          };
          readonly Product: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly category: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly currency: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly description: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly imageUrls: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
                readonly many: { readonly elementNullable: false };
              };
              readonly isActive: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/bool@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly priceCents: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly priceId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly productId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly stock: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: {
              readonly orderItems: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'OrderItem';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['productId'];
                };
              };
            };
            readonly storage: { readonly collection: 'products' };
          };
          readonly User: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly auth0_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly firstName: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly lastName: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly profilePictureUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: {
              readonly orders: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Order';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: { readonly collection: 'users' };
          };
        };
        readonly valueObjects: {
          readonly Address: {
            readonly fields: {
              readonly city: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly country: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly line1: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly postalCode: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
          };
        };
        readonly enum: {
          readonly Category: {
            readonly codecId: 'mongo/string@1';
            readonly members: readonly [
              { readonly name: 'ELECTRONICS'; readonly value: 'ELECTRONICS' },
              { readonly name: 'CLOTHING'; readonly value: 'CLOTHING' },
              { readonly name: 'HOME'; readonly value: 'HOME' },
              { readonly name: 'SPORTS'; readonly value: 'SPORTS' },
              { readonly name: 'OTHER'; readonly value: 'OTHER' },
            ];
          };
          readonly Currency: {
            readonly codecId: 'mongo/string@1';
            readonly members: readonly [
              { readonly name: 'EUR'; readonly value: 'EUR' },
              { readonly name: 'GBP'; readonly value: 'GBP' },
              { readonly name: 'TRY'; readonly value: 'TRY' },
            ];
          };
          readonly OrderStatus: {
            readonly codecId: 'mongo/string@1';
            readonly members: readonly [
              { readonly name: 'PENDING'; readonly value: 'PENDING' },
              { readonly name: 'PROCESSING'; readonly value: 'PROCESSING' },
              { readonly name: 'SHIPPED'; readonly value: 'SHIPPED' },
              { readonly name: 'DELIVERED'; readonly value: 'DELIVERED' },
              { readonly name: 'CANCELLED'; readonly value: 'CANCELLED' },
              { readonly name: 'RETURNED'; readonly value: 'RETURNED' },
              { readonly name: 'REFUNDED'; readonly value: 'REFUNDED' },
              { readonly name: 'EXPIRED'; readonly value: 'EXPIRED' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {};
  readonly extensions: {};
  readonly meta: {};
  readonly valueObjects: {
    readonly Address: {
      readonly fields: {
        readonly city: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly country: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly line1: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly postalCode: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
      };
    };
  };
  readonly profileHash: ProfileHash;
};

export type Contract = MongoContractWithTypeMaps<ContractBase, TypeMaps>;
