// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as MongoCodecTypes } from '@prisma/orm-mongo/target/codec-types';

import type {
  MongoCollection,
  MongoContractWithTypeMaps,
  MongoTypeMaps,
  RelationKeys,
} from '@prisma/orm-mongo/family-contract';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-mongo/contract/types';

export type StorageHash =
  StorageHashBase<'b0c6534da89c91d3c9467c12d66b23066ff27dab1a3c3bdf1b6829e04da903d3'>;
export type ExecutionHash =
  ExecutionHashBase<'7cc36d038b52cb90e381b72ac3413c91b17baa23fab2683d360639a1daca7f54'>;
export type ProfileHash =
  ProfileHashBase<'251b3ce23f6c9f561892e7c1af9d2cc941a13d64ba1aa7226b90036b09568cc3'>;

export type CodecTypes = MongoCodecTypes;

export type AddressOutput = {
  readonly city: CodecTypes['mongo/string@1']['output'];
  readonly country: CodecTypes['mongo/string@1']['output'];
  readonly line1: CodecTypes['mongo/string@1']['output'];
  readonly postalCode: CodecTypes['mongo/string@1']['output'];
};
export type AddressInput = {
  readonly city: CodecTypes['mongo/string@1']['input'];
  readonly country: CodecTypes['mongo/string@1']['input'];
  readonly line1: CodecTypes['mongo/string@1']['input'];
  readonly postalCode: CodecTypes['mongo/string@1']['input'];
};
export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly Cart: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly createdAt: CodecTypes['mongo/date@1']['output'];
      readonly updatedAt: CodecTypes['mongo/date@1']['output'];
      readonly userId: CodecTypes['mongo/string@1']['output'];
    };
    readonly CartItem: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly cartId: CodecTypes['mongo/objectId@1']['output'];
      readonly productId: CodecTypes['mongo/objectId@1']['output'];
      readonly quantity: CodecTypes['mongo/int32@1']['output'];
    };
    readonly Order: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly createdAt: CodecTypes['mongo/date@1']['output'];
      readonly status: CodecTypes['mongo/string@1']['output'];
      readonly updatedAt: CodecTypes['mongo/date@1']['output'];
      readonly userId: CodecTypes['mongo/objectId@1']['output'];
    };
    readonly OrderItem: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly createdAt: CodecTypes['mongo/date@1']['output'];
      readonly orderId: CodecTypes['mongo/objectId@1']['output'];
      readonly price: CodecTypes['mongo/double@1']['output'];
      readonly productId: CodecTypes['mongo/objectId@1']['output'];
      readonly quantity: CodecTypes['mongo/int32@1']['output'];
      readonly updatedAt: CodecTypes['mongo/date@1']['output'];
    };
    readonly Product: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly category: CodecTypes['mongo/string@1']['output'];
      readonly createdAt: CodecTypes['mongo/date@1']['output'];
      readonly images: ReadonlyArray<CodecTypes['mongo/string@1']['output']>;
      readonly isActive: CodecTypes['mongo/bool@1']['output'];
      readonly price: CodecTypes['mongo/double@1']['output'];
      readonly productBrand: CodecTypes['mongo/string@1']['output'];
      readonly productDescription: CodecTypes['mongo/string@1']['output'];
      readonly productName: CodecTypes['mongo/string@1']['output'];
      readonly stock: CodecTypes['mongo/int32@1']['output'];
      readonly stripePriceId: CodecTypes['mongo/string@1']['output'];
      readonly stripeProductId: CodecTypes['mongo/string@1']['output'];
      readonly updatedAt: CodecTypes['mongo/date@1']['output'];
    };
    readonly User: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly address: AddressOutput | null;
      readonly auth0UserId: CodecTypes['mongo/string@1']['output'];
      readonly cartId: CodecTypes['mongo/objectId@1']['output'] | null;
      readonly createdAt: CodecTypes['mongo/date@1']['output'];
      readonly email: CodecTypes['mongo/string@1']['output'];
      readonly emailVerified: CodecTypes['mongo/bool@1']['output'];
      readonly firstname: CodecTypes['mongo/string@1']['output'] | null;
      readonly lastname: CodecTypes['mongo/string@1']['output'] | null;
      readonly marketingConsent: CodecTypes['mongo/bool@1']['output'];
      readonly updatedAt: CodecTypes['mongo/date@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly Cart: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly createdAt: CodecTypes['mongo/date@1']['input'];
      readonly updatedAt: CodecTypes['mongo/date@1']['input'];
      readonly userId: CodecTypes['mongo/string@1']['input'];
    };
    readonly CartItem: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly cartId: CodecTypes['mongo/objectId@1']['input'];
      readonly productId: CodecTypes['mongo/objectId@1']['input'];
      readonly quantity: CodecTypes['mongo/int32@1']['input'];
    };
    readonly Order: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly createdAt: CodecTypes['mongo/date@1']['input'];
      readonly status: CodecTypes['mongo/string@1']['input'];
      readonly updatedAt: CodecTypes['mongo/date@1']['input'];
      readonly userId: CodecTypes['mongo/objectId@1']['input'];
    };
    readonly OrderItem: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly createdAt: CodecTypes['mongo/date@1']['input'];
      readonly orderId: CodecTypes['mongo/objectId@1']['input'];
      readonly price: CodecTypes['mongo/double@1']['input'];
      readonly productId: CodecTypes['mongo/objectId@1']['input'];
      readonly quantity: CodecTypes['mongo/int32@1']['input'];
      readonly updatedAt: CodecTypes['mongo/date@1']['input'];
    };
    readonly Product: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly category: CodecTypes['mongo/string@1']['input'];
      readonly createdAt: CodecTypes['mongo/date@1']['input'];
      readonly images: ReadonlyArray<CodecTypes['mongo/string@1']['input']>;
      readonly isActive: CodecTypes['mongo/bool@1']['input'];
      readonly price: CodecTypes['mongo/double@1']['input'];
      readonly productBrand: CodecTypes['mongo/string@1']['input'];
      readonly productDescription: CodecTypes['mongo/string@1']['input'];
      readonly productName: CodecTypes['mongo/string@1']['input'];
      readonly stock: CodecTypes['mongo/int32@1']['input'];
      readonly stripePriceId: CodecTypes['mongo/string@1']['input'];
      readonly stripeProductId: CodecTypes['mongo/string@1']['input'];
      readonly updatedAt: CodecTypes['mongo/date@1']['input'];
    };
    readonly User: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly address: AddressInput | null;
      readonly auth0UserId: CodecTypes['mongo/string@1']['input'];
      readonly cartId: CodecTypes['mongo/objectId@1']['input'] | null;
      readonly createdAt: CodecTypes['mongo/date@1']['input'];
      readonly email: CodecTypes['mongo/string@1']['input'];
      readonly emailVerified: CodecTypes['mongo/bool@1']['input'];
      readonly firstname: CodecTypes['mongo/string@1']['input'] | null;
      readonly lastname: CodecTypes['mongo/string@1']['input'] | null;
      readonly marketingConsent: CodecTypes['mongo/bool@1']['input'];
      readonly updatedAt: CodecTypes['mongo/date@1']['input'];
    };
  };
};

export namespace Models {
  export type unbound_Cart = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    createdAt: CodecTypes['mongo/date@1']['output'];
    updatedAt: CodecTypes['mongo/date@1']['output'];
    userId: CodecTypes['mongo/string@1']['output'];
    items: unbound_CartItem[];
    users: unbound_User[];
    readonly [RelationKeys]?: 'items' | 'users';
  };
  export type unbound_CartItem = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    cartId: CodecTypes['mongo/objectId@1']['output'];
    productId: CodecTypes['mongo/objectId@1']['output'];
    quantity: CodecTypes['mongo/int32@1']['output'];
    cart: unbound_Cart;
    product: unbound_Product;
    readonly [RelationKeys]?: 'cart' | 'product';
  };
  export type unbound_Order = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    createdAt: CodecTypes['mongo/date@1']['output'];
    status: CodecTypes['mongo/string@1']['output'];
    updatedAt: CodecTypes['mongo/date@1']['output'];
    userId: CodecTypes['mongo/objectId@1']['output'];
    orderItems: unbound_OrderItem[];
    user: unbound_User;
    readonly [RelationKeys]?: 'orderItems' | 'user';
  };
  export type unbound_OrderItem = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    createdAt: CodecTypes['mongo/date@1']['output'];
    orderId: CodecTypes['mongo/objectId@1']['output'];
    price: CodecTypes['mongo/double@1']['output'];
    productId: CodecTypes['mongo/objectId@1']['output'];
    quantity: CodecTypes['mongo/int32@1']['output'];
    updatedAt: CodecTypes['mongo/date@1']['output'];
    order: unbound_Order;
    product: unbound_Product;
    readonly [RelationKeys]?: 'order' | 'product';
  };
  export type unbound_Product = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    category: CodecTypes['mongo/string@1']['output'];
    createdAt: CodecTypes['mongo/date@1']['output'];
    images: ReadonlyArray<CodecTypes['mongo/string@1']['output']>;
    isActive: CodecTypes['mongo/bool@1']['output'];
    price: CodecTypes['mongo/double@1']['output'];
    productBrand: CodecTypes['mongo/string@1']['output'];
    productDescription: CodecTypes['mongo/string@1']['output'];
    productName: CodecTypes['mongo/string@1']['output'];
    stock: CodecTypes['mongo/int32@1']['output'];
    stripePriceId: CodecTypes['mongo/string@1']['output'];
    stripeProductId: CodecTypes['mongo/string@1']['output'];
    updatedAt: CodecTypes['mongo/date@1']['output'];
    cartItems: unbound_CartItem[];
    orderItems: unbound_OrderItem[];
    readonly [RelationKeys]?: 'cartItems' | 'orderItems';
  };
  export type unbound_User = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    address: AddressOutput | null;
    auth0UserId: CodecTypes['mongo/string@1']['output'];
    cartId: CodecTypes['mongo/objectId@1']['output'] | null;
    createdAt: CodecTypes['mongo/date@1']['output'];
    email: CodecTypes['mongo/string@1']['output'];
    emailVerified: CodecTypes['mongo/bool@1']['output'];
    firstname: CodecTypes['mongo/string@1']['output'] | null;
    lastname: CodecTypes['mongo/string@1']['output'] | null;
    marketingConsent: CodecTypes['mongo/bool@1']['output'];
    updatedAt: CodecTypes['mongo/date@1']['output'];
    cart: unbound_Cart | null;
    orders: unbound_Order[];
    readonly [RelationKeys]?: 'cart' | 'orders';
  };
}

export declare const models: {
  __unbound__: {
    Cart: Models.unbound_Cart;
    CartItem: Models.unbound_CartItem;
    Order: Models.unbound_Order;
    OrderItem: Models.unbound_OrderItem;
    Product: Models.unbound_Product;
    User: Models.unbound_User;
  };
};

export type TypeMaps = MongoTypeMaps<CodecTypes, FieldOutputTypes, FieldInputTypes>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'mongo-database';
        readonly entries: {
          readonly collection: {
            readonly cart_items: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly jsonSchema: {
                  readonly additionalProperties: false;
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly cartId: { readonly bsonType: 'objectId' };
                    readonly productId: { readonly bsonType: 'objectId' };
                    readonly quantity: { readonly bsonType: 'int' };
                  };
                  readonly required: readonly ['_id', 'cartId', 'productId', 'quantity'];
                };
                readonly kind: 'mongo-validator';
                readonly validationAction: 'error';
                readonly validationLevel: 'strict';
              };
            };
            readonly carts: {
              readonly indexes: readonly [
                {
                  readonly keys: readonly [{ readonly direction: 1; readonly field: 'userId' }];
                  readonly kind: 'mongo-index';
                  readonly unique: true;
                },
              ];
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly jsonSchema: {
                  readonly additionalProperties: false;
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly createdAt: { readonly bsonType: 'date' };
                    readonly updatedAt: { readonly bsonType: 'date' };
                    readonly userId: { readonly bsonType: 'string' };
                  };
                  readonly required: readonly ['_id', 'createdAt', 'updatedAt', 'userId'];
                };
                readonly kind: 'mongo-validator';
                readonly validationAction: 'error';
                readonly validationLevel: 'strict';
              };
            };
            readonly order_items: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly jsonSchema: {
                  readonly additionalProperties: false;
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly createdAt: { readonly bsonType: 'date' };
                    readonly orderId: { readonly bsonType: 'objectId' };
                    readonly price: { readonly bsonType: 'double' };
                    readonly productId: { readonly bsonType: 'objectId' };
                    readonly quantity: { readonly bsonType: 'int' };
                    readonly updatedAt: { readonly bsonType: 'date' };
                  };
                  readonly required: readonly [
                    '_id',
                    'createdAt',
                    'orderId',
                    'price',
                    'productId',
                    'quantity',
                    'updatedAt',
                  ];
                };
                readonly kind: 'mongo-validator';
                readonly validationAction: 'error';
                readonly validationLevel: 'strict';
              };
            };
            readonly orders: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly jsonSchema: {
                  readonly additionalProperties: false;
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly createdAt: { readonly bsonType: 'date' };
                    readonly status: { readonly bsonType: 'string' };
                    readonly updatedAt: { readonly bsonType: 'date' };
                    readonly userId: { readonly bsonType: 'objectId' };
                  };
                  readonly required: readonly ['_id', 'createdAt', 'status', 'updatedAt', 'userId'];
                };
                readonly kind: 'mongo-validator';
                readonly validationAction: 'error';
                readonly validationLevel: 'strict';
              };
            };
            readonly products: {
              readonly indexes: readonly [
                {
                  readonly keys: readonly [
                    { readonly direction: 1; readonly field: 'stripeProductId' },
                  ];
                  readonly kind: 'mongo-index';
                  readonly unique: true;
                },
              ];
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly jsonSchema: {
                  readonly additionalProperties: false;
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly category: { readonly bsonType: 'string' };
                    readonly createdAt: { readonly bsonType: 'date' };
                    readonly images: {
                      readonly bsonType: 'array';
                      readonly items: { readonly bsonType: 'string' };
                    };
                    readonly isActive: { readonly bsonType: 'bool' };
                    readonly price: { readonly bsonType: 'double' };
                    readonly productBrand: { readonly bsonType: 'string' };
                    readonly productDescription: { readonly bsonType: 'string' };
                    readonly productName: { readonly bsonType: 'string' };
                    readonly stock: { readonly bsonType: 'int' };
                    readonly stripePriceId: { readonly bsonType: 'string' };
                    readonly stripeProductId: { readonly bsonType: 'string' };
                    readonly updatedAt: { readonly bsonType: 'date' };
                  };
                  readonly required: readonly [
                    '_id',
                    'category',
                    'createdAt',
                    'images',
                    'isActive',
                    'price',
                    'productBrand',
                    'productDescription',
                    'productName',
                    'stock',
                    'stripePriceId',
                    'stripeProductId',
                    'updatedAt',
                  ];
                };
                readonly kind: 'mongo-validator';
                readonly validationAction: 'error';
                readonly validationLevel: 'strict';
              };
            };
            readonly users: {
              readonly indexes: readonly [
                {
                  readonly keys: readonly [
                    { readonly direction: 1; readonly field: 'auth0UserId' },
                  ];
                  readonly kind: 'mongo-index';
                  readonly unique: true;
                },
                {
                  readonly keys: readonly [{ readonly direction: 1; readonly field: 'email' }];
                  readonly kind: 'mongo-index';
                  readonly unique: true;
                },
              ];
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly jsonSchema: {
                  readonly additionalProperties: false;
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly address: {
                      readonly oneOf: readonly [
                        { readonly bsonType: 'null' },
                        {
                          readonly additionalProperties: false;
                          readonly bsonType: 'object';
                          readonly properties: {
                            readonly city: { readonly bsonType: 'string' };
                            readonly country: { readonly bsonType: 'string' };
                            readonly line1: { readonly bsonType: 'string' };
                            readonly postalCode: { readonly bsonType: 'string' };
                          };
                          readonly required: readonly ['city', 'country', 'line1', 'postalCode'];
                        },
                      ];
                    };
                    readonly auth0UserId: { readonly bsonType: 'string' };
                    readonly cartId: { readonly bsonType: readonly ['null', 'objectId'] };
                    readonly createdAt: { readonly bsonType: 'date' };
                    readonly email: { readonly bsonType: 'string' };
                    readonly emailVerified: { readonly bsonType: 'bool' };
                    readonly firstname: { readonly bsonType: readonly ['null', 'string'] };
                    readonly lastname: { readonly bsonType: readonly ['null', 'string'] };
                    readonly marketingConsent: { readonly bsonType: 'bool' };
                    readonly updatedAt: { readonly bsonType: 'date' };
                  };
                  readonly required: readonly [
                    '_id',
                    'auth0UserId',
                    'createdAt',
                    'email',
                    'emailVerified',
                    'marketingConsent',
                    'updatedAt',
                  ];
                };
                readonly kind: 'mongo-validator';
                readonly validationAction: 'error';
                readonly validationLevel: 'strict';
              };
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'mongo';
  readonly targetFamily: 'mongo';
  readonly roots: {
    readonly cart_items: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'CartItem';
    };
    readonly carts: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Cart' };
    readonly order_items: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'OrderItem';
    };
    readonly orders: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Order' };
    readonly products: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Product';
    };
    readonly users: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'User' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly Cart: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: {
              readonly items: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'CartItem';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['cartId'];
                };
              };
              readonly users: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['cartId'];
                };
              };
            };
            readonly storage: { readonly collection: 'carts' };
          };
          readonly CartItem: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly cartId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly productId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly quantity: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
            };
            readonly relations: {
              readonly cart: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Cart';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['cartId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
              readonly product: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Product';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['productId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
            };
            readonly storage: { readonly collection: 'cart_items' };
          };
          readonly Order: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
            };
            readonly relations: {
              readonly orderItems: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'OrderItem';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['orderId'];
                };
              };
              readonly user: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
            };
            readonly storage: { readonly collection: 'orders' };
          };
          readonly OrderItem: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly orderId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly price: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
              };
              readonly productId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly quantity: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: {
              readonly order: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Order';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['orderId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
              readonly product: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Product';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['productId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
            };
            readonly storage: { readonly collection: 'order_items' };
          };
          readonly Product: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly category: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly images: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
                readonly many: { readonly elementNullable: false };
              };
              readonly isActive: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/bool@1' };
              };
              readonly price: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
              };
              readonly productBrand: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly productDescription: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly productName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly stock: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly stripePriceId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly stripeProductId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: {
              readonly cartItems: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'CartItem';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['productId'];
                };
              };
              readonly orderItems: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'OrderItem';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['productId'];
                };
              };
            };
            readonly storage: { readonly collection: 'products' };
          };
          readonly User: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly address: {
                readonly nullable: true;
                readonly type: { readonly kind: 'valueObject'; readonly name: 'Address' };
              };
              readonly auth0UserId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly cartId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly emailVerified: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/bool@1' };
              };
              readonly firstname: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly lastname: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly marketingConsent: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/bool@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: {
              readonly cart: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Cart';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['cartId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
              readonly orders: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Order';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: { readonly collection: 'users' };
          };
        };
        readonly valueObjects: {
          readonly Address: {
            readonly fields: {
              readonly city: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly country: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly line1: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly postalCode: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {};
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly onCreate: { readonly id: 'timestampNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'carts';
            readonly field: 'createdAt';
            readonly namespace: '__unbound__';
          };
        },
        {
          readonly onCreate: { readonly id: 'timestampNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'timestampNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'carts';
            readonly field: 'updatedAt';
            readonly namespace: '__unbound__';
          };
        },
        {
          readonly onCreate: { readonly id: 'timestampNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'order_items';
            readonly field: 'createdAt';
            readonly namespace: '__unbound__';
          };
        },
        {
          readonly onCreate: { readonly id: 'timestampNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'timestampNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'order_items';
            readonly field: 'updatedAt';
            readonly namespace: '__unbound__';
          };
        },
        {
          readonly onCreate: { readonly id: 'timestampNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'orders';
            readonly field: 'createdAt';
            readonly namespace: '__unbound__';
          };
        },
        {
          readonly onCreate: { readonly id: 'timestampNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'timestampNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'orders';
            readonly field: 'updatedAt';
            readonly namespace: '__unbound__';
          };
        },
        {
          readonly onCreate: { readonly id: 'timestampNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'products';
            readonly field: 'createdAt';
            readonly namespace: '__unbound__';
          };
        },
        {
          readonly onCreate: { readonly id: 'timestampNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'timestampNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'products';
            readonly field: 'updatedAt';
            readonly namespace: '__unbound__';
          };
        },
        {
          readonly onCreate: { readonly id: 'timestampNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'users';
            readonly field: 'createdAt';
            readonly namespace: '__unbound__';
          };
        },
        {
          readonly onCreate: { readonly id: 'timestampNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'timestampNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'users';
            readonly field: 'updatedAt';
            readonly namespace: '__unbound__';
          };
        },
      ];
    };
  };
  readonly meta: {};
  readonly valueObjects: {
    readonly Address: {
      readonly fields: {
        readonly city: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly country: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly line1: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly postalCode: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
      };
    };
  };
  readonly profileHash: ProfileHash;
};

export type Contract = MongoContractWithTypeMaps<ContractBase, TypeMaps>;
